# Generated by Django 5.0 on 2023-12-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0002_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="-"),
            preserve_default=False,
        ),
    ]
