# Generated by Django 5.0 on 2023-12-25 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_collection_featured_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="membership_status",
            new_name="membership",
        ),
    ]
