# Generated by Django 5.0 on 2024-02-13 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
    ]
