# Generated by Django 5.0 on 2024-02-26 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_customer_options_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can Cancel Order")]},
        ),
    ]
